export const AFRIMARKET_CONFIG = {
FX_RATE: 1650,
SERVICE_FEE_PERCENT: 0.05,
SHIPPING_RATES: { US: 12, UK: 10, CA: 11, CN: 9 },
DUTY_RATES: { GADGETS: 0.20, CLOTHING: 0.10, GENERAL: 0.15 },
LOCAL_DELIVERY: { LAGOS: 3500, OUTSIDE_LAGOS: 6500 },
RESTRICTED_KEYWORDS: ["battery", "lithium", "liquid", "perfume", "powerbank", "flammable"]
};